#!/usr/bin/env bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Husky has been initiated..'

# Check Prettier standards
npm run lint:fix:all ||
(
        echo 'Due to Some ESLint Errors, Commit Has Been Stopped! 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Generate Complexity Report!
npm run --prefix server complexity || (
    echo 'Report Generated. Please check the updated ./server/complexity-report.md'
    true;
)

# If everything passes... Now we can commit
echo 'There is no threshold limit on complexity but you may set one.'

git add .

# If everything passes... Now we can commit
echo '[🟩🟩🟩] Successfully Commited!'