#!/usr/bin/env bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Husky has been initiated..'
echo '[🟩🟨🟨] Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Due to Wrong Prettier Formatting, Commit Has Been Stopped! ❌ 
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'Due to Some ESLint Errors, Commit Has Been Stopped! 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Typescript Generated Some Errors... Resolve Them And Try Again! ❌'
    false;
)

# Generate Complexity Report!
npm run check-complexity || (
    echo 'Report Generated....'
    true;
)

# If everything passes... Now we can commit
echo '[🟩🟩🟨] Code looks good... Trying to build now..'

npm run build ||
(
    echo 'Unfortunately, The Build Has Failed! ❌ 
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '[🟩🟩🟩] Successfully Commited!'